### ISSUE TITLE
✨FEATURE: Add Support for STM32 chips

### ISSUE THREAD

**Issue by Witty-Wizard** [Witty-Wizard/DriveMaster#2]
# Overview
Currently, this library only supports esp32-based boards, I am making this issue to add compatibility for STM32 chips.

## Plan
STMicroelectronics provides an Arduino core for STM32 boards, called STM32duino.
It ports the Arduino functions to be compatible with STM32 chips, additionally, it provides Wrapper for STM32 HAL and the STM32 LL Libraries.

For implementing DShot on STM32 we need to use a DMA along with a timer that would generate a PWM signal, for that we are going to use the LL libraries as they provide support for direct register manipulation, making it faster
## Task
- [ ] Read about STM32duino and the LL libraries
- [ ] Setup a timer to generate PWM pulse
- [ ] Setup DMA to change the PWM duty cycle.

## Reference 
- https://brushlesswhoop.com/dshot-and-bidirectional-dshot/
- https://betaflight.com/docs/development/Dshot
- https://github.com/bird-sanctuary/bluejay/wiki/z_archive:-EDT-Extended-DSHOT-Telemetry
- https://www.st.com/resource/en/user_manual/um1725-description-of-stm32f4-hal-and-lowlayer-drivers-stmicroelectronics.pdf
- https://wiki.st.com/stm32mcu/wiki/Getting_started_with_DMA
